### ISSUE TITLE
Metrics certificate is valid for localhost, not service name

### ISSUE THREAD

**Issue by vrutkovs** [openshift/cluster-kube-controller-manager-operator#136]
Metrics cannot be collected from controler-manager operator - Prometheus shows `Get https://10.129.0.10:8443/metrics: x509: certificate is valid for localhost, not metrics.openshift-kube-controller-manager-operator.svc` in Targets

**Comment by brancz** [comment]
> set the caFile to /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt which I guess is a path that the prometheus operator use to talk to this service.

Precisely. Thanks for bringing it up, we need to document this better in the integration guide.
