### ISSUE TITLE
–allocate-node-cidrs always been set to false

### ISSUE THREAD

**Issue by xuanyunhui** [openshift/cluster-kube-controller-manager-operator#399]
we are using Terway cni on Aibaba Cloud, so we need use kube-controller-manager to allocate  PodCIDR, we set follow config in KubeControllerManager.operator.openshift.io/v1, but no effect for us. 

unsupportedConfigOverrides:
    extendedArguments:
      allocate-node-cidrs:
      - "true"
      node-cidr-mask-size:
      - "23"

$ cat /etc/kubernetes/static-pod-resources/kube-controller-manager-pod-9/configmaps/config/config.yaml |jq
{
  "apiVersion": "kubecontrolplane.config.openshift.io/v1",
  "extendedArguments": {
    "allocate-node-cidrs": [
      "true"
    ],
    "cert-dir": [
      "/var/run/kubernetes"
    ],
    "cluster-cidr": [
      "10.108.128.0/18"
    ],
    "cluster-name": [
      "staging-mpcr4"
    ],
    "cluster-signing-cert-file": [
      "/etc/kubernetes/static-pod-certs/secrets/csr-signer/tls.crt"
    ],
    "cluster-signing-key-file": [
      "/etc/kubernetes/static-pod-certs/secrets/csr-signer/tls.key"
    ],
    "configure-cloud-routes": [
      "false"
    ],
    "controllers": [
      "*",
      "-ttl",
      "-bootstrapsigner",
      "-tokencleaner"
    ],
    "enable-dynamic-provisioning": [
      "true"
    ],
    "experimental-cluster-signing-duration": [
      "720h"
    ],
    "feature-gates": [
      "RotateKubeletServerCertificate=true",
      "SupportPodPidsLimit=true",
      "NodeDisruptionExclusion=true",
      "ServiceNodeExclusion=true",
      "SCTPSupport=true",
      "LegacyNodeRoleBehavior=false"
    ],
    "flex-volume-plugin-dir": [
      "/etc/kubernetes/kubelet-plugins/volume/exec"
    ],
    "kube-api-burst": [
      "300"
    ],
    "kube-api-qps": [
      "150"
    ],
    "leader-elect": [
      "true"
    ],
    "leader-elect-resource-lock": [
      "configmaps"
    ],
    "leader-elect-retry-period": [
      "3s"
    ],
    "node-cidr-mask-size": [
      "23"
    ],
    "port": [
      "0"
    ],
    "root-ca-file": [
      "/etc/kubernetes/static-pod-resources/configmaps/serviceaccount-ca/ca-bundle.crt"
    ],
    "secure-port": [
      "10257"
    ],
    "service-account-private-key-file": [
      "/etc/kubernetes/static-pod-resources/secrets/service-account-private-key/service-account.key"
    ],
    "service-cluster-ip-range": [
      "172.30.0.0/18"
    ],
    "use-service-account-credentials": [
      "true"
    ]
  },
  "kind": "KubeControllerManagerConfig",
  "serviceServingCert": {
    "certFile": "/etc/kubernetes/static-pod-resources/configmaps/service-ca/ca-bundle.crt"
  }
}

kcm logs:
I0417 05:50:25.193690       1 patch.go:65] FLAGSET: generic
I0417 05:50:25.193699       1 flags.go:33] FLAG: --allocate-node-cidrs="false"
I0417 05:50:25.193701       1 flags.go:33] FLAG: --allow-untagged-cloud="false"
I0417 05:50:25.193704       1 flags.go:33] FLAG: --cidr-allocator-type="RangeAllocator"
I0417 05:50:25.193707       1 flags.go:33] FLAG: --cloud-config=""
I0417 05:50:25.193709       1 flags.go:33] FLAG: --cloud-provider=""
I0417 05:50:25.193712       1 flags.go:33] FLAG: --cluster-cidr="10.108.128.0/18"
I0417 05:50:25.193715       1 flags.go:33] FLAG: --cluster-name="staging-mpcr4"
I0417 05:50:25.193717       1 flags.go:33] FLAG: --configure-cloud-routes="true"
I0417 05:50:25.193720       1 flags.go:33] FLAG: --controller-start-interval="0s"
I0417 05:50:25.193722       1 flags.go:33] FLAG: --controllers="[*,-ttl,-bootstrapsigner,-tokencleaner]"
I0417 05:50:25.193728       1 flags.go:33] FLAG: --external-cloud-volume-plugin=""
I0417 05:50:25.193731       1 flags.go:33] FLAG: --feature-gates="LegacyNodeRoleBehavior=false,NodeDisruptionExclusion=true,RotateKubeletServerCertificate=true,SCTPSupport=true,ServiceNodeExclusion=true,SupportPodPidsLimit=true"

**Comment by zhijianli88** [comment]
```
unsupportedConfigOverrides:
extendedArguments:
allocate-node-cidrs:
- "true"
node-cidr-mask-size:
- "23"
```
Hi, may i know how did you resolve this problem at last.
i also want to add addition arguments to k8s componnents
