### ISSUE TITLE
Installer pods are not retried on error

### ISSUE THREAD

**Issue by sttts** [openshift/cluster-kube-controller-manager-operator#72]
<img width="1013" alt="bildschirmfoto 2018-11-02 um 09 22 31" src="https://user-images.githubusercontent.com/730123/47901706-fad14900-de80-11e8-8855-4b6bc416f67d.png">

<img width="1676" alt="bildschirmfoto 2018-11-02 um 09 22 41" src="https://user-images.githubusercontent.com/730123/47901711-fe64d000-de80-11e8-8e0b-92b467d7f9a8.png">

**Comment by mfojtik** [comment]
retry mechanism added here: https://github.com/openshift/library-go/pull/74
