### ISSUE TITLE
Network CIDRs not observed from cluster config

### ISSUE THREAD

**Issue by sttts** [openshift/cluster-kube-controller-manager-operator#80]
We need the counterpart of https://github.com/openshift/cluster-kube-apiserver-operator/pull/74 for the controller manager. We have it for the bootstrapping phase (merged in https://github.com/openshift/cluster-kube-controller-manager-operator/pull/76), but not post-bootstrap.

**Comment by damemi** [comment]
/assign @damemi 

@sanchezl if you've already started work on this or want to take it feel free

**Comment by sttts** [comment]
/close

Fixed in https://github.com/openshift/cluster-kube-controller-manager-operator/pull/84.
